apiVersion: v1
kind: Pod
metadata:
 name: test
 spec:
  securityContext:
 	runAsUser: 4038 
 	fsGroup: 4038 
  containers:
	- name: tf-container
 	image: abhipec/iitg_kubernetes:p3_master_image_latest
 	# command: [ "/bin/sleep", "120" ]
 	resources:
 	 limits:
 	  nvidia.com/gpu: 1
 	volumeMounts:
 	 - name: nfs-data
 	 mountPath: /data
 volumes:
 - name: nfs-data
 hostPath:
 	path: /home/kubernetes/data/ibisht/
 	type: Directory
 restartPolicy: Never